
name: Print New Student Added

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  print-new-student:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    

      - name: Print new student(s) added
        run: |
          ls -ltr
          added_students=$(tail -n 1 student_list.txt)
          echo "New student(s) added in student_list.txt:"
          echo "${{ env.added_students }}"
